spring:
  redis:
    host: localhost
    port: 6379

  profiles:
    active: local

  freemarker:
    cache: false

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  jackson:
    serialization:
      fail-on-empty-beans: false

  datasource:
    url: jdbc:mysql://34.22.68.218:3306/test
    username: dmz
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 271384889161-o9cpsam4g7f56o3fval002i5u9ng7hk6.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email
logging:
  level:
    com.tutorial: debug

jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK
  refresh-secret: 7c7b4608afe05880d2cdbed9edb5c81ef8eac5271568253cbaa29ad06ed80009b319916fa1a5449dfbc679847669cd42f72599cf5c87c4f538f1feb4858e2eb3

sms:
  apiKey : NCSWUXEY6GVEX4US
  secretKey : OAEENSHT7XUHYHJLPHUIAWVWVJSE3XC7

neis:
  apiKey: 5decd9d597c54dd5a7410cc48fde6709

toss:
  secret: test_sk_7XZYkKL4MrjxQR2N2vo30zJwlEWR
